import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('database authorization, persistence, publication and invalidation',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth,public to authenticated,anon; grant execute on function auth.uid() to authenticated;`);
 await db.exec(await readFile(new URL('../supabase/001_schema.sql',import.meta.url),'utf8'));
 const ids=Array.from({length:12},(_,i)=>`00000000-0000-0000-0000-${String(i+1).padStart(12,'0')}`);
 for(let i=0;i<ids.length;i++)await db.query(`insert into auth.users values($1,$2,$3)`,[ids[i],`member${i}@example.com`,JSON.stringify({full_name:`Member ${i}`,is_admin:true})]);
 assert.equal((await db.query('select count(*)::int n from public.profiles where is_admin')).rows[0].n,0,'user metadata cannot grant admin');
 await db.query(`update public.profiles set is_admin=true where id=$1`,[ids[0]]);
 await db.query(`update public.profiles set skills=array['camera'],phone='123456'`);
 await db.query(`update public.profiles set skills=array['camera','producer'] where id=$1`,[ids[0]]);
 await db.query(`update public.profiles set skills=array['camera','ccu'] where id=$1`,[ids[1]]);
 await db.exec('set role authenticated');
 const as=async id=>db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[id]);
 for(const id of ids){await as(id);await db.query(`select public.submit_availability('2026-10-04',array['first'])`);}
 await as(ids[2]);
 assert.equal((await db.query('select * from public.profiles')).rows.length,1,'member cannot read others contact data');
 assert.equal((await db.query('select * from public.availability')).rows.length,4,'only own responses visible');
 assert.equal((await db.query(`select status from public.availability where service_id='second'`)).rows[0].status,'not_available');
 await assert.rejects(()=>db.query(`update public.profiles set is_admin=true`),/permission denied/);
 await assert.rejects(()=>db.query(`select public.manage_member($1,array['producer'],true)`,[ids[2]]),/Admin access required/);
 await assert.rejects(()=>db.query(`select public.save_schedule('2026-10-04','first','{}',false,0)`),/Admin access required/);
 await as(ids[0]);
 assert.equal((await db.query('select * from public.profiles')).rows.length,12);
 const assignments={producer:ids[0],ccu:ids[1],...Object.fromEntries(Array.from({length:8},(_,i)=>[`cam_${i+1}`,ids[i+2]]))};
 const save=(a,publish=true,revision=0,service='first')=>db.query(`select public.save_schedule('2026-10-04',$1,$2,$3,$4) id`,[service,JSON.stringify(a),publish,revision]);
 await assert.rejects(()=>save({cam_1:ids[0]}),/Fill all 10/);
 await assert.rejects(()=>save({...assignments,producer:ids[2]}),/ineligible/);
 await assert.rejects(()=>save({...assignments,cam_2:ids[2]}),/unique constraint/);
 await assert.rejects(()=>save(assignments,true,0,'second'),/ineligible/);
 const sid=(await save(assignments)).rows[0].id;
 assert.equal((await db.query('select * from public.assignments')).rows.length,10);
 await assert.rejects(()=>save(assignments,true,0),/Schedule changed/);
 await as(ids[2]);
 assert.equal((await db.query(`select * from public.published_schedule('2026-10-04')`)).rows.length,10);
 await db.query(`select public.submit_availability('2026-10-04','{}')`);
 assert.equal((await db.query(`select * from public.published_schedule('2026-10-04')`)).rows.length,0,'withdrawal unpublishes');
 assert.equal((await db.query('select * from public.schedules')).rows.length,0,'draft hidden from members');
 await as(ids[0]);
 const s=(await db.query('select * from public.schedules')).rows[0];assert.equal(s.status,'draft');assert.equal(s.revision,2);
 assert.equal((await db.query('select * from public.assignments')).rows.length,9);
 await assert.rejects(()=>save(assignments,true,2),/ineligible/);
 assignments.cam_1=ids[10];await save(assignments,true,2);
 await db.query(`select public.manage_member($1,'{}',true)`,[ids[1]]);
 assert.equal((await db.query('select status from public.schedules where id=$1',[sid])).rows[0].status,'draft');
 assert.equal((await db.query(`select * from public.assignments where position='ccu'`)).rows.length,0);
 await db.exec('reset role; set role anon');
 await assert.rejects(()=>db.query('select * from public.availability'),/permission denied/);
 await assert.rejects(()=>db.query(`select public.submit_availability('2026-10-04','{}')`),/permission denied/);
 await db.close();
});
